export const SET_SELECTED_FORMATION = 'SET_SELECTED_FORMATION';
export const CHANGE_FORMATION = 'CHANGE_FORMATION';

export const SET_SELECTED_SHIRT_COLOR = 'SET_SELECTED_SHIRT_COLOR';
export const CHANGE_SHIRT_COLOR = 'CHANGE_SHIRT_COLOR';

export const SET_SELECTED_SHORTS_COLOR = 'SET_SELECTED_SHORTS_COLOR';
export const CHANGE_SHORTS_COLOR = 'CHANGE_SHORTS_COLOR';

export const CHANGE_PLAYER_LABEL = 'CHANGE_PLAYER_LABEL';
export const CHANGE_PLAYER_NUMBER = 'CHANGE_PLAYER_NUMBER';

export const MOVE_PLAYER = 'MOVE_PLAYER';
